package loginReg;


import java.awt.BasicStroke;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PATRICIA
 */
public class registerform extends javax.swing.JFrame {

    // Simulated database for email and username uniqueness check
   

    public registerform() {
        initComponents();
        setResizable(false);
        setSize(680, 429);
    }
    
    Color hover = new Color(0, 153, 153);
    Color defbutton = new Color(204,255,204);

    Border empty = BorderFactory.createEmptyBorder();

    void buttonBorderAnimation(JPanel panel) {
        panel.setBackground(hover);
        panel.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        panel.setBorder(BorderFactory.createStrokeBorder(new BasicStroke(2.0f)));
    }

    void buttonDefaultColor(JPanel panel) {
        panel.setBackground(defbutton);
        panel.setBorder(empty);
    }
    
    public static String passwordHash(String password) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA"); // Use SHA-256
            md.update(password.getBytes());
            byte[] rbt = md.digest();
            StringBuilder sb = new StringBuilder();

            for (byte b : rbt) {
                sb.append(String.format("%02x", b));
            }
            return sb.toString();
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace(); // Log the error properly
            return null;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        enterfn = new javax.swing.JTextField();
        ln = new javax.swing.JLabel();
        enterln = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        enteremail = new javax.swing.JTextField();
        pass = new javax.swing.JLabel();
        confirm = new javax.swing.JLabel();
        buttonreg = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        enterconfirm = new javax.swing.JPasswordField();
        enterpass = new javax.swing.JPasswordField();
        buttonreg1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        user = new javax.swing.JComboBox<>();
        confirm2 = new javax.swing.JLabel();
        fn1 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        fn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Please Register ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main.setBackground(new java.awt.Color(0, 51, 51));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterfn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        enterfn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        enterfn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterfnActionPerformed(evt);
            }
        });
        main.add(enterfn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 260, 30));

        ln.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ln.setForeground(new java.awt.Color(255, 255, 255));
        ln.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ln.setText("Last name:");
        main.add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 90, 30));

        enterln.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        enterln.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        enterln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterlnActionPerformed(evt);
            }
        });
        main.add(enterln, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 260, 30));

        email.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        email.setText("Email:");
        main.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 90, 30));

        enteremail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        enteremail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        enteremail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enteremailActionPerformed(evt);
            }
        });
        main.add(enteremail, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 260, 30));

        pass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pass.setForeground(new java.awt.Color(255, 255, 255));
        pass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pass.setText("Password:");
        main.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 90, 30));

        confirm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        confirm.setForeground(new java.awt.Color(255, 255, 255));
        confirm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirm.setText("User Type:");
        main.add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 90, 30));

        buttonreg.setBackground(new java.awt.Color(204, 255, 204));
        buttonreg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        buttonreg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonregMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonregMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonregMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Cancel");

        javax.swing.GroupLayout buttonregLayout = new javax.swing.GroupLayout(buttonreg);
        buttonreg.setLayout(buttonregLayout);
        buttonregLayout.setHorizontalGroup(
            buttonregLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
        );
        buttonregLayout.setVerticalGroup(
            buttonregLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        main.add(buttonreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 100, 30));

        enterconfirm.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        enterconfirm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        main.add(enterconfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 260, 30));

        enterpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        enterpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        enterpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enterpassKeyPressed(evt);
            }
        });
        main.add(enterpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 260, 30));

        buttonreg1.setBackground(new java.awt.Color(204, 255, 204));
        buttonreg1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        buttonreg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonreg1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonreg1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonreg1MouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Register");

        javax.swing.GroupLayout buttonreg1Layout = new javax.swing.GroupLayout(buttonreg1);
        buttonreg1.setLayout(buttonreg1Layout);
        buttonreg1Layout.setHorizontalGroup(
            buttonreg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
        );
        buttonreg1Layout.setVerticalGroup(
            buttonreg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        main.add(buttonreg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 100, 30));

        user.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        user.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User\t", "Admin" }));
        user.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        main.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 260, 30));

        confirm2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        confirm2.setForeground(new java.awt.Color(255, 255, 255));
        confirm2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirm2.setText("C-Password:");
        main.add(confirm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 90, 30));

        fn1.setBackground(new java.awt.Color(255, 255, 255));
        fn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fn1.setForeground(new java.awt.Color(255, 255, 255));
        fn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fn1.setText("First name:");
        main.add(fn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 100, 30));

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setFont(new java.awt.Font("Bernard MT Condensed", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Create your Account");
        main.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 275, 30));

        fn.setBackground(new java.awt.Color(255, 255, 255));
        fn.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        fn.setForeground(new java.awt.Color(255, 255, 255));
        fn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fn.setText("- For a better place -");
        main.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 130, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hagdan.png"))); // NOI18N
        main.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonreg1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonreg1MouseExited
        buttonDefaultColor(buttonreg1);
    }//GEN-LAST:event_buttonreg1MouseExited

    private void buttonreg1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonreg1MouseEntered
        buttonBorderAnimation(buttonreg1);
    }//GEN-LAST:event_buttonreg1MouseEntered

    private void buttonreg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonreg1MouseClicked
        String firstName = enterfn.getText().trim();
        String lastName = enterln.getText().trim();
        String email = enteremail.getText().trim();
        String password = passwordHash(enterpass.getText());
        String use_type = user.getSelectedItem().toString();
        String user_status = "Pending";

        if (firstName.isEmpty() || lastName.isEmpty() || email.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!email.matches("^[a-zA-Z0-9._%+-]+@gmail\\.com$")) {
            JOptionPane.showMessageDialog(this, "Please enter a valid Gmail address (example@gmail.com)", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (password.length() < 8) {
            JOptionPane.showMessageDialog(this, "Password should have at least 8 characters.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

       
        String url = "jdbc:mysql://localhost:3306/obaob_db";
        String user = "root";
        String pass = "";

        try {

            Connection conn = DriverManager.getConnection(url, user, pass);
            if (isEmailDuplicate(conn, email)) {
                JOptionPane.showMessageDialog(this, "Email already exists. Please use a different email.", "Error", JOptionPane.ERROR_MESSAGE);
                conn.close();
                return;
            }

            String sql = "INSERT INTO user_table (firstName, lastName, email, password, use_type, user_status) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement pstmt = conn.prepareStatement(sql);

            pstmt.setString(1, firstName);
            pstmt.setString(2, lastName);
            pstmt.setString(3, email);
            pstmt.setString(4, password);
            pstmt.setString(5, use_type);
            pstmt.setString(6, user_status);
            
            int rowsInserted = pstmt.executeUpdate();
            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(this, "Registration Successful!");
                this.dispose();
                new loginform().setVisible(true);
            }

            pstmt.close();
            conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonreg1MouseClicked

    private void buttonregMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonregMouseExited
        buttonDefaultColor(buttonreg);
    }//GEN-LAST:event_buttonregMouseExited

    private void buttonregMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonregMouseEntered
        buttonBorderAnimation(buttonreg);
    }//GEN-LAST:event_buttonregMouseEntered

    private void buttonregMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonregMouseClicked
        loginform logForm = new loginform();
        logForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonregMouseClicked

    private void enteremailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enteremailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enteremailActionPerformed

    private void enterlnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterlnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterlnActionPerformed

    private void enterfnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterfnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterfnActionPerformed

    private void enterpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enterpassKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterpassKeyPressed
        private boolean isEmailDuplicate(Connection conn, String email) {
        boolean exists = false;
        String query = "SELECT COUNT(*) FROM user_table WHERE email = ?";

        try (PreparedStatement stmt = conn.prepareStatement(query)) {
            stmt.setString(1, email);
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                exists = rs.getInt(1) > 0;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return exists;
    }
        

       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonreg;
    private javax.swing.JPanel buttonreg1;
    private javax.swing.JLabel confirm;
    private javax.swing.JLabel confirm2;
    private javax.swing.JLabel email;
    private javax.swing.JPasswordField enterconfirm;
    private javax.swing.JTextField enteremail;
    private javax.swing.JTextField enterfn;
    private javax.swing.JTextField enterln;
    private javax.swing.JPasswordField enterpass;
    private javax.swing.JLabel fn;
    private javax.swing.JLabel fn1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel ln;
    private javax.swing.JPanel main;
    private javax.swing.JLabel pass;
    private javax.swing.JLabel title;
    private javax.swing.JComboBox<String> user;
    // End of variables declaration//GEN-END:variables
}
