/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminPackage;

import config.Session;
import config.dbConnector;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author PATRICIA
 */
public class admindescription extends javax.swing.JFrame {
     private String fullname;
     private static String userImagePath = null;
     private int r_id;
    private String b_id;
    private Timestamp dateSettled; // ✅ Change from String to Timestamp

     
    public admindescription(String fullname, String imgPath) {
        initComponents();
        this.fullname = fullname;
        setSize(970, 590);
        setResizable(false);
        
        setLocationRelativeTo(null);
        
        userImagePath = imgPath;
    }
  public admindescription(int r_id, int b_id, Timestamp dateSettled) {
    initComponents(); 

    this.r_id = r_id;
    this.b_id = String.valueOf(b_id); // ✅ Convert int to String
    this.dateSettled = dateSettled; // ✅ Keep dateSettled as a Timestamp

    // ✅ Display values in JLabels
    txtr_id.setText(String.valueOf(r_id));
    txtb_id.setText(this.b_id); // ✅ Already a String
    datesettled.setText(dateSettled.toString()); 
}
    
    
     private void logActivity(int user_id, String action) {
        String sql = "INSERT INTO system_logs (user_id, logs_action, logs_date) VALUES (?, ?, NOW())";
        dbConnector db = new dbConnector();

        try (Connection conn = db.getConnection();
             PreparedStatement pst = conn.prepareStatement(sql)) {
            pst.setInt(1, user_id);
            pst.setString(2, action);
            pst.executeUpdate();
        } catch (SQLException e) {
            System.err.println("Error logging activity: " + e.getMessage());
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ln1 = new javax.swing.JLabel();
        datesettled = new javax.swing.JTextField();
        ln2 = new javax.swing.JLabel();
        decription = new javax.swing.JTextField();
        generatereports = new javax.swing.JButton();
        ln3 = new javax.swing.JLabel();
        txtb_id = new javax.swing.JTextField();
        ln4 = new javax.swing.JLabel();
        txtr_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main.setBackground(new java.awt.Color(0, 51, 51));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(0, 153, 153));
        header.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BLOTTER DETAILS");
        header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 980, 30));

        main.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 40));

        ln1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ln1.setForeground(new java.awt.Color(255, 255, 255));
        ln1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ln1.setText("Date Settled:");
        main.add(ln1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 110, 30));

        datesettled.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        datesettled.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        datesettled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datesettledActionPerformed(evt);
            }
        });
        main.add(datesettled, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 220, 40));

        ln2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ln2.setForeground(new java.awt.Color(255, 255, 255));
        ln2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ln2.setText("Description:");
        main.add(ln2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 160, 30));

        decription.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        decription.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        decription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decriptionActionPerformed(evt);
            }
        });
        main.add(decription, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 760, 240));

        generatereports.setText("Generate Report");
        generatereports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generatereportsMouseClicked(evt);
            }
        });
        main.add(generatereports, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 480, 140, 30));

        ln3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ln3.setForeground(new java.awt.Color(255, 255, 255));
        ln3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ln3.setText("Blotter ID:");
        main.add(ln3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 80, 30));

        txtb_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtb_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtb_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtb_idActionPerformed(evt);
            }
        });
        main.add(txtb_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 70, 30));

        ln4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ln4.setForeground(new java.awt.Color(255, 255, 255));
        ln4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ln4.setText("Record ID:");
        main.add(ln4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 80, 30));

        txtr_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtr_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtr_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtr_idActionPerformed(evt);
            }
        });
        main.add(txtr_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 70, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void datesettledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datesettledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datesettledActionPerformed

    private void decriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_decriptionActionPerformed

    private void generatereportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generatereportsMouseClicked
        String description = decription.getText().trim(); // Get user input

        if (description.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a description!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String url = "jdbc:mysql://localhost:3306/obaob_db";
        String user = "root";
        String pass = "";

        try (Connection conn = DriverManager.getConnection(url, user, pass);
                PreparedStatement updateStmt = conn.prepareStatement(
                        "UPDATE reports_table SET r_description = ? WHERE r_id = ?")) {

            updateStmt.setString(1, description);
            updateStmt.setInt(2, r_id);

            int rowsUpdated = updateStmt.executeUpdate();

            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(null, "Report updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                
                 Session session = Session.getInstance();
            int userId = session.getUid();

            if (userId != -1) {
                logActivity(userId, "Admin Updated Report (r_id: " + r_id + ") with description.");
            } else {
                System.err.println("Session user ID not set. Cannot log report update activity.");
            }
            
                // ✅ Retrieve full blotter details
                PreparedStatement stmt = conn.prepareStatement(
                        "SELECT b.b_id, c.c_fname, c.c_lname, b.b_fname, b.b_incident, b.b_location, "
                        + "b.b_witness1, b.b_witness2, b.b_date, r.r_datesettled "
                        + // ✅ Include r_datesettled
                        "FROM blotter_table b "
                        + "JOIN citizen_table c ON b.c_id = c.c_id "
                        + "JOIN reports_table r ON b.b_id = r.b_id "
                        + // ✅ Join reports_table to get r_datesettled
                        "WHERE b.b_id = ?");

                stmt.setInt(1, Integer.parseInt(b_id));
                ResultSet rs = stmt.executeQuery();

                if (rs.next()) {
                    String susFullName = rs.getString("c_fname") + " " + rs.getString("c_lname");
                    String complainant = rs.getString("b_fname");
                    String incident = rs.getString("b_incident");
                    String location = rs.getString("b_location");
                    String witness1 = rs.getString("b_witness1");
                    String witness2 = rs.getString("b_witness2");
                    String dateReported = rs.getTimestamp("b_date").toString();
                    Timestamp dateSettled = rs.getTimestamp("r_datesettled"); // ✅ Retrieve as Timestamp

                    new adminReport(susFullName, complainant, incident, location, witness1, witness2, dateReported, description, dateSettled).setVisible(true);
                    this.dispose();
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(admindescription.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_generatereportsMouseClicked

    private void txtb_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtb_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtb_idActionPerformed

    private void txtr_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtr_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtr_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admindescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admindescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admindescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admindescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 String imgPath = "path/to/default/image.png";
                 new admindescription("Admin User", imgPath).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField datesettled;
    private javax.swing.JTextField decription;
    private javax.swing.JButton generatereports;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel ln1;
    private javax.swing.JLabel ln2;
    private javax.swing.JLabel ln3;
    private javax.swing.JLabel ln4;
    private javax.swing.JPanel main;
    private javax.swing.JTextField txtb_id;
    private javax.swing.JTextField txtr_id;
    // End of variables declaration//GEN-END:variables
}
