/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminPackage;

import config.Session;
import config.dbConnector;
import config.panelPrinter;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Timestamp;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author PATRICIA
 */
public class adminReport extends javax.swing.JFrame {

    private String fullname;
    private static String userImagePath = null;
    private JPanel reportPanel;

    /**
     * Creates new form adminReport
     */
    public adminReport(String fullname, String imgPath) {
        this.fullname = fullname;

        setResizable(false);
        setSize(860, 770);

        reportPanel = bodycolorPanel;

        initComponents();

        setLocationRelativeTo(null);

        userImagePath = imgPath;

    }
    
      private void logActivity(int user_id, String action) {
        String sql = "INSERT INTO system_logs (user_id, logs_action, logs_date) VALUES (?, ?, NOW())";
        dbConnector db = new dbConnector();

        try (Connection conn = db.getConnection();
             PreparedStatement pst = conn.prepareStatement(sql)) {
            pst.setInt(1, user_id);
            pst.setString(2, action);
            pst.executeUpdate();
        } catch (SQLException e) {
            System.err.println("Error logging activity: " + e.getMessage());
        }
    }
    
    

    public adminReport(String susFullName, String complainant, String incident, String location,
            String witness1, String witness2, String dateReported, String description, Timestamp dateSettled) {
        initComponents();

        suspectsname.setText(susFullName);
        complainantsname.setText(complainant);
        complanantsname10.setText(complainant);
        incident1.setText(incident);
        location1.setText(location);
        txtwitness1.setText(witness1);
        txtwitness2.setText(witness2);
        datereported.setText(dateReported);
        description10.setText(description);
        datesettled.setText(dateSettled.toString()); // ✅ Convert Timestamp to String for display
         
        if (reportPanel == null) {
            reportPanel = new JPanel(); // If it's missing, initialize it
        }

        JButton printButton = new JButton("Print");
        printButton.setBounds(50, 500, 100, 30);
        printButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                printReport();
            }
        });

        this.add(printButton); // ✅ Add button to JFrameJButton printButton = new JButton("Print");
        printButton.setBounds(50, 500, 100, 30);
        printButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                printReport();
            }
        });

        this.add(printButton);

    }

    private void printReport() {
        panelPrinter printer = new panelPrinter(bodycolorPanel); // ✅ Replace jPanel1 with your actual panel name
        printer.printPanel();
        
        Session session = Session.getInstance();
    int userId = session.getUid();

    if (userId != -1) {
        logActivity(userId, "Printed a report from the admin panel.");
    } else {
        System.err.println("Session user ID not set. Cannot log print activity.");
    }
    }

    Color navcolor = new Color(0, 51, 51);
    Color headcolor = new Color(0, 153, 153);
    Color bodycolor = new Color(0, 153, 153);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        save = new javax.swing.JLabel();
        printButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        bodycolorPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        description10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        datereported = new javax.swing.JLabel();
        complainantsname = new javax.swing.JLabel();
        incident1 = new javax.swing.JLabel();
        txtwitness2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        location1 = new javax.swing.JLabel();
        txtwitness1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        suspectsname = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        datesettled = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        complanantsname10 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        adminname = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(850, 770));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-left-50.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("____________________");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 190, 40));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Save As");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 190, 40));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Share");
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 190, 40));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Export");
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 190, 40));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Options");
        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 190, 40));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Close");
        jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 190, 40));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Accounts");
        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 190, 40));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Feedback");
        jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 190, 40));

        save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save.setText("Save");
        save.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 190, 40));

        printButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        printButton1.setText("Print");
        printButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(printButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 190, 40));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bodycolorPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodycolorPanel.setPreferredSize(new java.awt.Dimension(100, 100));
        bodycolorPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/download (2).png"))); // NOI18N
        bodycolorPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 11, -1, 101));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/download (1).png"))); // NOI18N
        bodycolorPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 11, 73, 101));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Republic of the Philippines");
        bodycolorPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 20, 260, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Region VII");
        bodycolorPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 41, 260, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Province of Cebu");
        bodycolorPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 62, 260, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Witness 2:");
        bodycolorPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 90, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("_____________________________________________________________________");
        bodycolorPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 140, 485, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("B A R A N G A Y  B L O T T E R");
        bodycolorPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 485, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("OFFICE  OF  THE  PUNONG  BARANGAY");
        bodycolorPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 118, 485, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Municipality of Minglanilla");
        bodycolorPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 78, 260, 20));

        description10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        description10.setText("display description");
        bodycolorPanel.add(description10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 510, 60));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Date & Time Reported:");
        bodycolorPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 170, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Complainant's Name:");
        bodycolorPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 130, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Incident:");
        bodycolorPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 70, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Location:");
        bodycolorPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 70, 20));

        datereported.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        datereported.setText("     display date");
        bodycolorPanel.add(datereported, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 200, 20));

        complainantsname.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        complainantsname.setText("display name");
        bodycolorPanel.add(complainantsname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 200, 20));

        incident1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        incident1.setText("  display incident");
        bodycolorPanel.add(incident1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 420, 20));

        txtwitness2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtwitness2.setText("display winess2");
        bodycolorPanel.add(txtwitness2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 200, 20));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Description:");
        bodycolorPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 90, 20));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Witness 1:");
        bodycolorPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 90, 20));

        location1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        location1.setText("  display location");
        bodycolorPanel.add(location1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 200, 20));

        txtwitness1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtwitness1.setText("display winess1");
        bodycolorPanel.add(txtwitness1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 200, 20));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Suspect's Name:");
        bodycolorPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, 20));

        suspectsname.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        suspectsname.setText("display susname");
        bodycolorPanel.add(suspectsname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 200, 20));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Reported by:");
        bodycolorPanel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, 170, 20));

        datesettled.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        datesettled.setText("display date");
        bodycolorPanel.add(datesettled, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, 200, 20));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Date & Time Settled:");
        bodycolorPanel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 170, 20));

        complanantsname10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        complanantsname10.setText("Complainant's Name");
        bodycolorPanel.add(complanantsname10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 190, 40));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Recorded by:");
        bodycolorPanel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 630, 170, 20));

        adminname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminname.setText("Patricia Obaob");
        bodycolorPanel.add(adminname, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 650, 190, 40));

        jPanel2.add(bodycolorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 570, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void printButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButton1ActionPerformed
        printReport();
    }//GEN-LAST:event_printButton1ActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        new adminBlotter(fullname, userImagePath).setVisible(true);
        this.dispose();

    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String imgPath = "path/to/default/image.png";
                new adminReport("Admin User", imgPath).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminname;
    private javax.swing.JLabel back;
    private javax.swing.JPanel bodycolorPanel;
    private javax.swing.JLabel complainantsname;
    private javax.swing.JLabel complanantsname10;
    private javax.swing.JLabel datereported;
    private javax.swing.JLabel datesettled;
    private javax.swing.JLabel description10;
    private javax.swing.JLabel incident1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel location1;
    private javax.swing.JButton printButton1;
    private javax.swing.JLabel save;
    private javax.swing.JLabel suspectsname;
    private javax.swing.JLabel txtwitness1;
    private javax.swing.JLabel txtwitness2;
    // End of variables declaration//GEN-END:variables
}
