/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminPackage;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author PATRICIA
 */
public class adminBlotterCRUD extends javax.swing.JFrame {
      private String fullname;
    /**
     * Creates new form adminBlotterCRUD
     */
    public adminBlotterCRUD(String fullname) {
        this.fullname = fullname;
        initComponents();
        setSize(970, 540);
        setResizable(false);
        
    }
    
   public adminBlotterCRUD(int c_id, String b_fname, String b_incident,String b_location, String b_status, String b_date, String b_witness1,String b_witness2) {
        initComponents(); 
        
        
    txtc_id.setText(String.valueOf(c_id));   
    txtComplainant.setText(b_fname);
    txtincident.setText(b_incident);
    txtlocation.setText(b_location);
    cmbstatus.setSelectedItem(b_status);
    txtdate.setText(b_date); 
    txtdate.setEnabled(false); 
    txtwitness1.setText(b_witness1);
    txtwitness2.setText(b_witness2);
    
    
    showCitizenDetails(c_id);
    }
    Color navcolor = new Color(204,255,204);
    Color headcolor = new Color(0,51,51);
    Color bodycolor = new Color(0,153,153);
    
    private void showCitizenDetails(int citizenId) {
    String url = "jdbc:mysql://localhost:3306/obaob_db";
    String user = "root";
    String pass = "";

    try (Connection conn = DriverManager.getConnection(url, user, pass)) {
        String query = "SELECT citizen_table.c_fname, citizen_table.c_lname FROM blotter_table "
                     + "JOIN citizen_table ON blotter_table.c_id = citizen_table.c_id "
                     + "WHERE blotter_table.b_id = ?";
        
        PreparedStatement ps = conn.prepareStatement(query);
        ps.setInt(1, citizenId);
        ResultSet rs = ps.executeQuery();
        
        if (rs.next()) {
            txtc_fname.setText(rs.getString("c_fname"));
            txtc_fname.setEditable(false);  
            txtc_lname.setText(rs.getString("c_lname"));
            txtc_lname.setEditable(false);  
        } else {
            JOptionPane.showMessageDialog(null, "No complainant found for this blotter ID.");
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error loading complainant details: " + ex.getMessage());
    }
}


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addbutton2 = new javax.swing.JPanel();
        edit = new javax.swing.JLabel();
        deletebutton = new javax.swing.JPanel();
        add = new javax.swing.JLabel();
        refresh = new javax.swing.JPanel();
        refresh1 = new javax.swing.JLabel();
        editbutton1 = new javax.swing.JPanel();
        edit1 = new javax.swing.JLabel();
        fn1 = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        txtComplainant = new javax.swing.JTextField();
        txtincident = new javax.swing.JTextField();
        email2 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        ln = new javax.swing.JLabel();
        email1 = new javax.swing.JLabel();
        txtc_lname = new javax.swing.JTextField();
        txtlocation = new javax.swing.JTextField();
        email3 = new javax.swing.JLabel();
        cmbstatus = new javax.swing.JComboBox<>();
        ln1 = new javax.swing.JLabel();
        txtwitness1 = new javax.swing.JTextField();
        ln2 = new javax.swing.JLabel();
        txtwitness2 = new javax.swing.JTextField();
        back = new javax.swing.JPanel();
        edit2 = new javax.swing.JLabel();
        txtc_fname = new javax.swing.JTextField();
        ln3 = new javax.swing.JLabel();
        txtc_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main.setBackground(new java.awt.Color(0, 51, 51));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(0, 153, 153));
        header.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BLOTTER DETAILS");
        header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 980, 30));

        main.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 40));

        addbutton2.setBackground(new java.awt.Color(204, 255, 204));
        addbutton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        addbutton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbutton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addbutton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addbutton2MouseExited(evt);
            }
        });

        edit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        edit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        edit.setText("ADD");

        javax.swing.GroupLayout addbutton2Layout = new javax.swing.GroupLayout(addbutton2);
        addbutton2.setLayout(addbutton2Layout);
        addbutton2Layout.setHorizontalGroup(
            addbutton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addbutton2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        addbutton2Layout.setVerticalGroup(
            addbutton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addbutton2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        main.add(addbutton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 80, 30));

        deletebutton.setBackground(new java.awt.Color(204, 255, 204));
        deletebutton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        deletebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletebuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deletebuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deletebuttonMouseExited(evt);
            }
        });

        add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add.setText("DELETE");

        javax.swing.GroupLayout deletebuttonLayout = new javax.swing.GroupLayout(deletebutton);
        deletebutton.setLayout(deletebuttonLayout);
        deletebuttonLayout.setHorizontalGroup(
            deletebuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deletebuttonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        deletebuttonLayout.setVerticalGroup(
            deletebuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deletebuttonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        main.add(deletebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 80, 30));

        refresh.setBackground(new java.awt.Color(204, 255, 204));
        refresh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                refreshMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                refreshMouseExited(evt);
            }
        });

        refresh1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        refresh1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        refresh1.setText("REFRESH");

        javax.swing.GroupLayout refreshLayout = new javax.swing.GroupLayout(refresh);
        refresh.setLayout(refreshLayout);
        refreshLayout.setHorizontalGroup(
            refreshLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, refreshLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(refresh1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        refreshLayout.setVerticalGroup(
            refreshLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, refreshLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(refresh1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        main.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, -1, -1));

        editbutton1.setBackground(new java.awt.Color(204, 255, 204));
        editbutton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        editbutton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editbutton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editbutton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editbutton1MouseExited(evt);
            }
        });

        edit1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        edit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        edit1.setText("EDIT");

        javax.swing.GroupLayout editbutton1Layout = new javax.swing.GroupLayout(editbutton1);
        editbutton1.setLayout(editbutton1Layout);
        editbutton1Layout.setHorizontalGroup(
            editbutton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editbutton1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(edit1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        editbutton1Layout.setVerticalGroup(
            editbutton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editbutton1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(edit1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        main.add(editbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 80, 30));

        fn1.setBackground(new java.awt.Color(255, 255, 255));
        fn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fn1.setForeground(new java.awt.Color(255, 255, 255));
        fn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fn1.setText("Complainant:");
        main.add(fn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 130, 40));

        email.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        email.setText("Incident Type:");
        main.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 130, 30));

        txtComplainant.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtComplainant.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtComplainant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplainantActionPerformed(evt);
            }
        });
        main.add(txtComplainant, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 260, 40));

        txtincident.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtincident.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtincident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtincidentActionPerformed(evt);
            }
        });
        main.add(txtincident, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 260, 40));

        email2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        email2.setForeground(new java.awt.Color(255, 255, 255));
        email2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        email2.setText("Date Reported:");
        main.add(email2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 120, 30));

        txtdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateActionPerformed(evt);
            }
        });
        main.add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 260, 40));

        ln.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ln.setForeground(new java.awt.Color(255, 255, 255));
        ln.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ln.setText("Suspect Name:");
        main.add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 120, 30));

        email1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        email1.setForeground(new java.awt.Color(255, 255, 255));
        email1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        email1.setText("Status:");
        main.add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 120, 40));

        txtc_lname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtc_lname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtc_lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtc_lnameActionPerformed(evt);
            }
        });
        main.add(txtc_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 120, 30));

        txtlocation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtlocation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtlocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlocationActionPerformed(evt);
            }
        });
        main.add(txtlocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 260, 40));

        email3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        email3.setForeground(new java.awt.Color(255, 255, 255));
        email3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        email3.setText("Location:");
        main.add(email3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 110, 30));

        cmbstatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Ongoing", "Settled" }));
        main.add(cmbstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 260, 40));

        ln1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ln1.setForeground(new java.awt.Color(255, 255, 255));
        ln1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ln1.setText("Witness 1:");
        main.add(ln1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 120, 30));

        txtwitness1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtwitness1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtwitness1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtwitness1ActionPerformed(evt);
            }
        });
        main.add(txtwitness1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 260, 40));

        ln2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ln2.setForeground(new java.awt.Color(255, 255, 255));
        ln2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ln2.setText("Witness 2:");
        main.add(ln2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 120, 40));

        txtwitness2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtwitness2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtwitness2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtwitness2ActionPerformed(evt);
            }
        });
        main.add(txtwitness2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 260, 40));

        back.setBackground(new java.awt.Color(204, 255, 204));
        back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });

        edit2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        edit2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        edit2.setText("BACK");

        javax.swing.GroupLayout backLayout = new javax.swing.GroupLayout(back);
        back.setLayout(backLayout);
        backLayout.setHorizontalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(edit2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        backLayout.setVerticalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(edit2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        main.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 80, 30));

        txtc_fname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtc_fname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtc_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtc_fnameActionPerformed(evt);
            }
        });
        main.add(txtc_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 120, 30));

        ln3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ln3.setForeground(new java.awt.Color(255, 255, 255));
        ln3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ln3.setText("Enter Citizen (id):");
        main.add(ln3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 120, 30));

        txtc_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtc_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtc_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtc_idActionPerformed(evt);
            }
        });
        main.add(txtc_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addbutton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbutton2MouseClicked
       
    }//GEN-LAST:event_addbutton2MouseClicked

    private void addbutton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbutton2MouseEntered
        addbutton2.setBackground(bodycolor);
    }//GEN-LAST:event_addbutton2MouseEntered

    private void addbutton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbutton2MouseExited
        addbutton2.setBackground(navcolor);
    }//GEN-LAST:event_addbutton2MouseExited

    private void deletebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletebuttonMouseClicked

    }//GEN-LAST:event_deletebuttonMouseClicked

    private void deletebuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletebuttonMouseEntered
        deletebutton.setBackground(bodycolor);
    }//GEN-LAST:event_deletebuttonMouseEntered

    private void deletebuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletebuttonMouseExited
        deletebutton.setBackground(navcolor);
    }//GEN-LAST:event_deletebuttonMouseExited

    private void refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseClicked

    }//GEN-LAST:event_refreshMouseClicked

    private void refreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseEntered
        refresh.setBackground(bodycolor);
    }//GEN-LAST:event_refreshMouseEntered

    private void refreshMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseExited
        refresh.setBackground(navcolor);
    }//GEN-LAST:event_refreshMouseExited

    private void editbutton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editbutton1MouseClicked

        
        
        
    }//GEN-LAST:event_editbutton1MouseClicked

    private void editbutton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editbutton1MouseEntered
        editbutton1.setBackground(bodycolor);
    }//GEN-LAST:event_editbutton1MouseEntered

    private void editbutton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editbutton1MouseExited
        editbutton1.setBackground(navcolor);
    }//GEN-LAST:event_editbutton1MouseExited

    private void txtComplainantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplainantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplainantActionPerformed

    private void txtincidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtincidentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtincidentActionPerformed

    private void txtdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateActionPerformed

    private void txtc_lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtc_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtc_lnameActionPerformed

    private void txtlocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlocationActionPerformed

    private void txtwitness1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtwitness1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtwitness1ActionPerformed

    private void txtwitness2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtwitness2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtwitness2ActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
            new adminBlotter(fullname).setVisible(true);
            this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
         back.setBackground(bodycolor);
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        back.setBackground(navcolor);
    }//GEN-LAST:event_backMouseExited

    private void txtc_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtc_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtc_fnameActionPerformed

    private void txtc_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtc_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtc_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminBlotterCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminBlotterCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminBlotterCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminBlotterCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminBlotterCRUD("Admin User").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add;
    private javax.swing.JPanel addbutton2;
    private javax.swing.JPanel back;
    private javax.swing.JComboBox<String> cmbstatus;
    private javax.swing.JPanel deletebutton;
    private javax.swing.JLabel edit;
    private javax.swing.JLabel edit1;
    private javax.swing.JLabel edit2;
    private javax.swing.JPanel editbutton1;
    private javax.swing.JLabel email;
    private javax.swing.JLabel email1;
    private javax.swing.JLabel email2;
    private javax.swing.JLabel email3;
    private javax.swing.JLabel fn1;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel ln;
    private javax.swing.JLabel ln1;
    private javax.swing.JLabel ln2;
    private javax.swing.JLabel ln3;
    private javax.swing.JPanel main;
    private javax.swing.JPanel refresh;
    private javax.swing.JLabel refresh1;
    private javax.swing.JTextField txtComplainant;
    private javax.swing.JTextField txtc_fname;
    private javax.swing.JTextField txtc_id;
    private javax.swing.JTextField txtc_lname;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtincident;
    private javax.swing.JTextField txtlocation;
    private javax.swing.JTextField txtwitness1;
    private javax.swing.JTextField txtwitness2;
    // End of variables declaration//GEN-END:variables
}
