
import config.dbConnector;
import java.awt.BasicStroke;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PATRICIA
 */
public class loginform extends javax.swing.JFrame {

    /**
     * Creates new form loginform
     */
    public loginform() {
        initComponents();
        setResizable(false);
        
    }
     Color hover = new Color(0,153,153);
     Color defbutton = new Color(0,51,51);
     
     Border empty = BorderFactory.createEmptyBorder();
     
     void buttonBorderAnimation(JPanel panel){
     panel.setBackground(hover);
     panel.setBorder(BorderFactory.createLineBorder(Color.BLACK));
     panel.setBorder(BorderFactory.createStrokeBorder(new BasicStroke(2.0f)));
     }
    
     void buttonDefaultColor(JPanel panel){
     panel.setBackground(defbutton);
     panel.setBorder(empty);
     }
     
     private boolean validateLogin() {
        String user = enterusername.getText().trim();
        String password = new String(enterpass.getPassword());

        // Validation Checks
        if (user.isEmpty()|| password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        if (password.length() < 8) {
            JOptionPane.showMessageDialog(this, "Password must be at least 8 characters long!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        enterusername = new javax.swing.JTextField();
        pass = new javax.swing.JLabel();
        enterpass = new javax.swing.JPasswordField();
        logbg = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        canbg = new javax.swing.JPanel();
        cancel = new javax.swing.JLabel();
        click = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main.setBackground(new java.awt.Color(204, 255, 204));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("SIGN IN");
        main.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 680, 40));

        username.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        username.setText("Username:");
        main.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 92, -1));

        enterusername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        enterusername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        main.add(enterusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 234, 35));

        pass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pass.setText("Password:");
        main.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 92, -1));

        enterpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        enterpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        main.add(enterpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 234, 34));

        logbg.setBackground(new java.awt.Color(0, 51, 51));
        logbg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        logbg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logbgMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logbgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logbgMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Login");

        javax.swing.GroupLayout logbgLayout = new javax.swing.GroupLayout(logbg);
        logbg.setLayout(logbgLayout);
        logbgLayout.setHorizontalGroup(
            logbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
        );
        logbgLayout.setVerticalGroup(
            logbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logbgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        main.add(logbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        canbg.setBackground(new java.awt.Color(0, 51, 51));
        canbg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        canbg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canbgMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                canbgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                canbgMouseExited(evt);
            }
        });

        cancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancel.setText("Cancel");

        javax.swing.GroupLayout canbgLayout = new javax.swing.GroupLayout(canbg);
        canbg.setLayout(canbgLayout);
        canbgLayout.setHorizontalGroup(
            canbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
        );
        canbgLayout.setVerticalGroup(
            canbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(canbgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        main.add(canbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        click.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        click.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        click.setText("Click Here to Register");
        click.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clickMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clickMouseExited(evt);
            }
        });
        main.add(click, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 234, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logbgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logbgMouseExited
        buttonDefaultColor(logbg);
    }//GEN-LAST:event_logbgMouseExited

    private void logbgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logbgMouseEntered
        buttonBorderAnimation(logbg);
    }//GEN-LAST:event_logbgMouseEntered

    private void logbgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logbgMouseClicked
        String email = enterusername.getText();
        String password = new String(enterpass.getPassword());

        if (email.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter both email and password.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String sql = "SELECT * FROM user_table WHERE email = ? AND password = ?";

        dbConnector db = new dbConnector(); // Create an instance of dbConnector

        try (Connection conn = db.getConnection();  // Get connection from dbConnector
            PreparedStatement pst = conn.prepareStatement(sql)) {

            pst.setString(1, email);
            pst.setString(2, password);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "Login successful!", "Success", JOptionPane.INFORMATION_MESSAGE);

                String use_type = rs.getString("use_type");

                if (use_type.equals("Admin")) {
                    adminPage admin = new adminPage();
                    admin.setVisible(true);
                } else {
                    userPage user = new userPage();
                    user.setVisible(true);
                }

                this.dispose();

            } else {
                JOptionPane.showMessageDialog(this, "Incorrect username or password.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_logbgMouseClicked

    private void canbgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canbgMouseExited
        buttonDefaultColor(canbg);
    }//GEN-LAST:event_canbgMouseExited

    private void canbgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canbgMouseEntered
        buttonBorderAnimation(canbg);
    }//GEN-LAST:event_canbgMouseEntered

    private void canbgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canbgMouseClicked
        int response = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to cancel the login process?",
            "Confirm Cancel",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (response == JOptionPane.YES_OPTION) {
            // Close the login window or perform any necessary action
            this.dispose(); // Closes the current window
        }
    }//GEN-LAST:event_canbgMouseClicked

    private void clickMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickMouseExited
        click.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_clickMouseExited

    private void clickMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickMouseEntered
        click.setForeground(java.awt.Color.BLUE);
    }//GEN-LAST:event_clickMouseEntered

    private void clickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickMouseClicked
        registerform regForm = new registerform();
        regForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_clickMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel canbg;
    private javax.swing.JLabel cancel;
    private javax.swing.JLabel click;
    private javax.swing.JPasswordField enterpass;
    private javax.swing.JTextField enterusername;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel logbg;
    private javax.swing.JPanel main;
    private javax.swing.JLabel pass;
    private javax.swing.JLabel title;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
