
import java.awt.BasicStroke;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.border.Border;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PATRICIA
 */
public class loginform extends javax.swing.JFrame {

    /**
     * Creates new form loginform
     */
    public loginform() {
        initComponents();
    }
     Color hover = new Color(0,51,102);
     Color defbutton = new Color(240,240,240);
     
     Border empty = BorderFactory.createEmptyBorder();
     
     void buttonBorderAnimation(JPanel panel){
     panel.setBackground(hover);
     panel.setBorder(BorderFactory.createLineBorder(Color.BLACK));
     panel.setBorder(BorderFactory.createStrokeBorder(new BasicStroke(2.0f)));
     }
    
     void buttonDefaultColor(JPanel panel){
     panel.setBackground(defbutton);
     panel.setBorder(empty);
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        pass = new javax.swing.JPasswordField();
        usname = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        paswor = new javax.swing.JLabel();
        register = new javax.swing.JLabel();
        text = new javax.swing.JLabel();
        prof = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cancel = new javax.swing.JPanel();
        cancee = new javax.swing.JLabel();
        cancel1 = new javax.swing.JPanel();
        cancee1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main.setBackground(new java.awt.Color(0, 51, 102));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        main.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 150, 20));

        usname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usnameActionPerformed(evt);
            }
        });
        main.add(usname, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 150, 20));

        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Username:");
        main.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 70, 20));

        paswor.setForeground(new java.awt.Color(255, 255, 255));
        paswor.setText("Password:");
        main.add(paswor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 80, 20));

        register.setForeground(new java.awt.Color(255, 255, 255));
        register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        register.setText("Click Here to Register");
        main.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 150, 30));

        text.setBackground(new java.awt.Color(51, 51, 0));
        text.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        text.setForeground(new java.awt.Color(255, 255, 255));
        text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text.setText("Login");
        main.add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 66, 130, 20));

        prof.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prof.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-people-40.png"))); // NOI18N
        main.add(prof, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 40, 30));

        welcome.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        welcome.setForeground(new java.awt.Color(255, 255, 255));
        welcome.setText("Welcome to my system!");
        main.add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 210, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/download.png"))); // NOI18N
        main.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 170, 200));

        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelMouseExited(evt);
            }
        });
        cancel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancee.setText("Login");
        cancel.add(cancee, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 40, 20));

        main.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 50, 20));

        cancel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancel1MouseExited(evt);
            }
        });
        cancel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancee1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancee1.setText("Cancel");
        cancel1.add(cancee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 40, 20));

        main.add(cancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 50, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void usnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usnameActionPerformed

    private void cancel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel1MouseEntered
        buttonBorderAnimation(cancel1);
    }//GEN-LAST:event_cancel1MouseEntered

    private void cancel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel1MouseExited
        buttonDefaultColor(cancel1);
    }//GEN-LAST:event_cancel1MouseExited

    private void cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseEntered
        buttonBorderAnimation(cancel);
    }//GEN-LAST:event_cancelMouseEntered

    private void cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseExited
        buttonDefaultColor(cancel);
    }//GEN-LAST:event_cancelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cancee;
    private javax.swing.JLabel cancee1;
    private javax.swing.JPanel cancel;
    private javax.swing.JPanel cancel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel main;
    private javax.swing.JLabel name;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel paswor;
    private javax.swing.JLabel prof;
    private javax.swing.JLabel register;
    private javax.swing.JLabel text;
    private javax.swing.JTextField usname;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
